### ISSUE TITLE
"Hide Minimap With Chat" Behaviour is Reversed

### ISSUE THREAD

**Issue by ajhakra** [UNDEAD-B0T/collapsible-modern-chat#4]
Hey,

It seems when using the "Hide Minimap With Chat" option, the behaviour seems to be flipped. Whenever I collapse my chat, my minimap appears and when I expand my chat, the minimap disappears.

Steps to re-produce:

1. Enable "Collapsible Modern Chat" plugin
2. Toggle on "Hide Minimap With Chat"
3. Collapse and expand chat to see the flipped behaviour

Expected outcome:
- Minimap disappears alongside the chat

Actual outcome:
- Minimap opens when chat is collapsed
- Minimap closes when chat is opened

**Comment by UNDEAD-B0T** [comment]
this is intended but in the future there will be an option to select whether you want chat closed = hide minimap or chat open = hide minimap

currently working on a revamp of the plugin thats much more customizable/advanced and then going to fix suggestions like this but its probably going to be awhile so tbd
